apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  #commonName: k8s-multi.com
  commonName: 35.224.172.111
  dnsNames:
    # - k8s-multi.com
    # - www.k8s-multi.com
    - 35.224.172.111
  acme:
    config:
      - http01: 
          ingressClass: nginx
        domains:
          # - k8s-multi.com
          # - www.k8s-multi.com
          - 35.224.172.111